global:
  scrape_interval: 15s # 每 15 秒抓一次數據

scrape_configs:
  - job_name: 'nuxt-app'
    scheme: 'https'
    static_configs:
      - targets: ['host.docker.internal:3000'] # 3000 是你 Nuxt 執行的 Port
    metrics_path: '/metrics' # nuxt-prometheus 預設的數據路徑
    tls_config:
      ca_file: '/etc/prometheus/rootCA.pem' # 你的 CA 憑證
      cert_file: '/etc/prometheus/localhost.pem' # 你的客戶端
      key_file: '/etc/prometheus/localhost-key.pem' # 你的客戶端密鑰
      server_name: 'localhost' # 強制校驗憑證上的 localhost 名稱
