/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicWidget: typeof import('./components/Widgets/BasicWidget.vue')['default']
    FakeContent: typeof import('./components/StackedCard/FakeContent.vue')['default']
    FlipCard: typeof import('./components/StackedCard/FlipCard.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Steps: typeof import('./components/Steps/index.vue')['default']
    VueDemoAside: typeof import('./components/VueDemo/Main/VueDemoAside.vue')['default']
    VueDemoBlock: typeof import('./components/VueDemo/Main/VueDemoBlock.vue')['default']
    VueDemoCode: typeof import('./components/VueDemo/Main/VueDemoCode.vue')['default']
    VueDemoHeaderDetails: typeof import('./components/VueDemo/Header/VueDemoHeaderDetails.vue')['default']
    VueDemoHeaderList: typeof import('./components/VueDemo/Header/VueDemoHeaderList.vue')['default']
    VueDemoHeaderLogo: typeof import('./components/VueDemo/Header/VueDemoHeaderLogo.vue')['default']
    VueDemoHeaderSearch: typeof import('./components/VueDemo/Header/VueDemoHeaderSearch.vue')['default']
    VueDemoIntro: typeof import('./components/VueDemo/Main/content/VueDemoIntro.vue')['default']
    VueDemoMain: typeof import('./components/VueDemo/Main/VueDemoMain.vue')['default']
    VueDemoNavigationDetails: typeof import('./components/VueDemo/Navigation/VueDemoNavigationDetails.vue')['default']
    VueDemoNavigationList: typeof import('./components/VueDemo/Navigation/VueDemoNavigationList.vue')['default']
    VueDemoPath: typeof import('./components/VueDemo/Main/content/VueDemoPath.vue')['default']
    VueDemoProgressive: typeof import('./components/VueDemo/Main/content/VueDemoProgressive.vue')['default']
    VueDemoQA: typeof import('./components/VueDemo/Main/content/VueDemoQA.vue')['default']
    VueDemoSingle: typeof import('./components/VueDemo/Main/content/VueDemoSingle.vue')['default']
    VueDemoStyle: typeof import('./components/VueDemo/Main/content/VueDemoStyle.vue')['default']
    VueDemoVue: typeof import('./components/VueDemo/Main/content/VueDemoVue.vue')['default']
  }
}
